INSERT INTO planets (NAME, VERSION, CREATIONTIME, UPDATETIME)
VALUES
    ('Tatooine',1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bespin',1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('FOREST MOON OF ENDOR', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ILUM', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('POLIS MASSA', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MANDALORE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO planets_questions (PLANET_ID, QUESTION_ID)
VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (2, 4),
    (2, 5),
    (2, 6),
    (3, 7),
    (3, 8),
    (3, 9),
    (4, 10),
    (4, 11),
    (4, 12),
    (5, 13),
    (5, 14),
    (5, 15),
    (6, 16),
    (6, 17),
    (6, 18);

INSERT INTO questions (DESCRIPTION, SCORE, VERSION, CREATIONTIME, UPDATETIME)
VALUES
    ('C3PO appears for the first time in this world?', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Who buys C3PO and R2D2 in Tattoine?', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Who assembled C3PO?', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Who reassembled C3PO after the shooting?', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What happened to Han Solo while on Bespin?', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('From what planet did they evacuate before Bespin?', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What species is native to the Forest Moon of Endor?', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What special status do the Ewoks give C-3PO?', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What is the relationship between the Forest Moon of Endor and the nearby Death Star II?', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What resource is Ilum best known for?', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What role does Ilum play in Jedi training?', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What is the name of the ceremony where Jedi younglings retrieve their kyber cristals from Ilum?', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What significant event took place on Polis Massa?', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Which of the following best describes Polis Massa`s terrain?', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What was the Polis Massans primary form of comunication', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What is Mandalore primarily known for in the galaxy?', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What is the name of the dark weapon that symbolizes leadership among Mandalorians?', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('What event is known as the “Great Purge” of Mandalore?', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO answers (DESCRIPTION, CORRECT, VERSION, CREATIONTIME, UPDATETIME)
VALUES

    ('True', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('False', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Owen Lars and Luke Skywalker', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Shmi', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('R2D2', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Obi-Wan Kenobi', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Anakin Skywalker', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Shmi', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Cliegg Lars', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The Sand people', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Chewbacca', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('R2D2', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Han Solo', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Leia', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('He was frozen in carbonite', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Stayed behind fighting stormtroopers', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Hoth', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Mandalore', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Aldeeran', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Dagobah', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Ewoks', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Jawas', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
    ('Tusken Raiders', true, 1,  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Wookies', false, 1,  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('War leader', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Village elder', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Deity', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Chieftain', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Endor powers the Death Star II', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Endor´s orbit is used to hide the Death Star II', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Endor is used as a testing ground for Death Star weapons', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The Death Star II is stationed to protect Endor', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Kyber Crystals', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Spice', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP ),
    ('Durasteel', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Tibanna gas', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('It is the location for the Jedi Academy', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('It is where Jedi go to find kyber crystals for their lightsabers', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('It is a testing ground for Jedi combat skills', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('It is the site for Jedi Council meetings', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The Initiation', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The Gathering', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The Trial of Crystals', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The rite of passage', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The signing of the Galactic Concordance', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The birth of Luke and Leia', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The construction of the death star', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The execution of Order 66', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Rocky asteroid with scattered ruins', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Lush green forests', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Icy tundra', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Volcanic Wastelands', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Verbal Speech', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Holographic signals', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Telepathy', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Binary Code', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Its strong connection to te force', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Its legendary warrior culture', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Its advanced medical facilities', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Its powerful navy', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Lightsaber of Mandalore', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Darksaber', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Mandalorian Blade', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Shadow Saber', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The Republic’s invasion of Mandalore', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The Empire’s assault that decimated the Mandalorians and seized their Beskar', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The Jedi’s attack to destroy Mandalorian warriors', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('The Sith’s destruction of the Mandalorian homeworld', false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);




INSERT INTO questions_answers (QUESTION_ID, ANSWER_ID)
VALUES
    (1, 1),
    (1, 2),
    (2, 3),
    (2, 4),
    (2, 5),
    (2, 6),
    (3, 7),
    (3, 8),
    (3, 9),
    (3, 10),
    (4, 11),
    (4, 12),
    (4, 13),
    (4, 14),
    (5, 15),
    (5, 16),
    (6, 17),
    (6, 18),
    (6, 19),
    (6, 20),
    (7, 21),
    (7, 22),
    (7, 23),
    (7, 24),
    (8, 25),
    (8, 26),
    (8, 27),
    (8, 28),
    (9, 29),
    (9, 30),
    (9, 31),
    (9, 32),
    (10,33),
    (10,34),
    (10,35),
    (10,36),
    (11,37),
    (11,38),
    (11,39),
    (11,40),
    (12,41),
    (12,42),
    (12,43),
    (12,44),
    (13,45),
    (13,46),
    (13,47),
    (13,48),
    (14,49),
    (14,50),
    (14,51),
    (14,52),
    (15,53),
    (15,54),
    (15,55),
    (15,56),
    (16,57),
    (16,58),
    (16,59),
    (16,60),
    (17,61),
    (17,62),
    (17,63),
    (17,64),
    (18,65),
    (18,66),
    (18,67),
    (18,69);


